[JENKINS-60406] Replace RUN_SCRIPTS with ADMINISTER
jenkinsci/workflow-cps-global-lib-plugin pull request #122
Opened 2021-11-10 22:11 UTC by bitwiseman

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-11-10 22:16 UTC, car-roll approved these changes

2021-11-10 22:17 UTC, jglick commented on workflow-cps-global-lib.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Can you ignore this please?

2021-11-10 22:18 UTC, jglick requested changes
Forgot https://github.com/jenkinsci/workflow-cps-global-lib-plugin/blob/a1de00ea889a91e3cb4d143c0ba5efb6a7815db3/src/main/resources/org/jenkinsci/plugins/workflow/libs/GlobalLibraries/config.jelly#L28

2021-11-10 22:21 UTC, jtnord approved these changes
Looks good to me.

It may be the code can be further cleaned up as global configuration should never be called unless you have administer, but that will open a can of worms so this looks like a reasonable step that can be potentially refined at some point in the future.

2021-11-10 23:14 UTC, olamy approved these changes
LGTM (no much more to say than @jglick comments)

2021-11-11 00:29 UTC, bitwiseman commented
@jglick Addressed feedback.

2021-11-11 16:19 UTC, car-roll commented
looks like @jglick 's comment has been addressed, going ahead to merge

2021-11-11 16:19 UTC, merged