JENKINS-38609: Shared Library non ROOT support
jenkinsci/workflow-cps-global-lib-plugin pull request #99
Opened 2020-09-21 12:40 UTC by heyleke

This is a new implementation for JENKINS-38609, which makes it possible to load libraries from a specified relative path. Only touching files mentioned in review of #84

2020-09-21 13:08 UTC, heyleke commented
/review @dwnusbaum

2020-09-24 21:14 UTC, dwnusbaum requested changes
Thanks for the PR! I added some minor comments about refactoring the setters, and a more important comment about making sure this PR doesn't introduce security issues, which needs to be addressed.

2020-09-25 08:15 UTC, heyleke commented on src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
> +            lease.path.child(libBase).copyRecursiveTo("src/**/*.groovy,vars/*.groovy,vars/*.txt,resources/", excludes, target);
I will check this 'offline', it is indeed not 'secure'

2020-09-26 16:21 UTC, heyleke commented on src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
> +            lease.path.child(libBase).copyRecursiveTo("src/**/*.groovy,vars/*.groovy,vars/*.txt,resources/", excludes, target);
taken care of in new commit (I squashed everything again)

2020-10-05 07:06 UTC, heyleke commented
ping @dwnusbaum can you please re-review after changes done?

2020-10-19 21:44 UTC, dwnusbaum commented
@heyleke I filed https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/101 based on this PR with various minor changes (the commit is still attributed to you), if you can review that PR it would be appreciated.

2021-03-29 12:20 UTC, mahmoud-ashi commented
Hey all. Can we move this forward? It has been pending since some time now :). This change would really be nice for my use case. Thanks.

2021-09-15 18:21 UTC, jglick commented
@car-roll since #101 was merged, should this not be closed?

2021-09-16 21:57 UTC, closed without merging